### ISSUE TITLE
Make unconscious spectator functionality optional and togglable by player

### ISSUE THREAD

**Issue by Piesa** [ArmaForces/Mods#217]
For immersion sake it would be useful to allow users to voluntarily opt out from unconscious spectator functionality as some players might enjoy (even if only on some missions) the vanilla experience of having hearing only during unconsciousness. Preferably togglable by a shortcut in unconsciousness state, or just in options.

**Comment by 3Mydlo3** [comment]
Adding a shortcut would be a lot of work, but toggle in options seems like an easy one.
