### ISSUE TITLE
Custom smoke grenade particle sizes

### ISSUE THREAD

**Issue by veteran29** [ArmaForces/Mods#77]
I've overheard some convo from our players that vanilla smokes seem too small but splendid smoke seems too big. We should research making something in-between.

**Comment by SzwedzikPL** [comment]
Try https://github.com/SzwedzikPL/A3CS/blob/master/addons/smoke/CfgCloudlets.hpp

It's based on splendid smoke but tweaked a little for better FPS. Maybe you'll like it.

**Comment by veteran29** [comment]
Thanks, this seems useful, I like the idea of increasing the interval of smoke on destruction effects for better perf.
